### ISSUE TITLE
Some sites always return a hit

### ISSUE THREAD

**Issue by SOC-guy** [senran101604/sagemode#3]
Great idea and Initiative! However some sites always seem to give a hit. I tried several times with random usernames, and these always pop up. I have no idea how to get around this nor fix it, that's something for far more clever and bright minds to do.

cat L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g.txt

############################# 11/10/2023, 08:22 AM #############################

https://www.facebook.com/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://www.khanacademy.org/profile/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://steamcommunity.com/id/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://www.ebay.com/usr/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://medium.com/@L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://www.instagram.com/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://www.codecademy.com/profiles/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://www.mixcloud.com/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://account.xbox.com/en-US/Profile?gamertag=L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://socialclub.rockstargames.com/member/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g
https://www.coursera.org/user/L2IPgt4fDIsTPpjPjn3Qf3LC4MrYQpOKK8ECCHScg7g

**Comment by senran101604** [comment]
most of the false results are fixed now, but Facebook and Khan Academy sites are still prone to false positives
